-- ===========================================================================
-- POSTGRESQL COMPATIBLE DATABASE INITIALIZATION SCRIPT
-- System: Local Inventory and POS Management System (Phase 0 Blueprint)
-- Optimization: Future-proofed with native UUIDs and Synchronization parameters
-- ===========================================================================

-- Step 0: Create a reusable function to automatically update 'updated_at' timestamps
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;;

-- 1. TABLE: system_settings
CREATE TABLE IF NOT EXISTS system_settings (
    settings_id UUID PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    logo_path TEXT,
    primary_color VARCHAR(7) DEFAULT '#000000',
    secondary_color VARCHAR(7) DEFAULT '#FFFFFF',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_synced BOOLEAN DEFAULT FALSE
);;

COMMENT ON TABLE system_settings IS 'Stores global application configuration. This table will always contain exactly one row.';;
COMMENT ON COLUMN system_settings.settings_id IS 'Unique UUID generated by the application framework.';;
COMMENT ON COLUMN system_settings.company_name IS 'The name displayed on the user interface and printed on invoices.';;
COMMENT ON COLUMN system_settings.logo_path IS 'File path to the locally stored logo image file (e.g., C:/app/assets/logo.png).';;
COMMENT ON COLUMN system_settings.primary_color IS 'Hex code for primary UI elements (buttons, headers).';;
COMMENT ON COLUMN system_settings.secondary_color IS 'Hex code for accent UI elements.';;
COMMENT ON COLUMN system_settings.updated_at IS 'Tracks when the configuration was last modified.';;
COMMENT ON COLUMN system_settings.is_synced IS 'Sync status flag for future multi-system architecture.';;

DROP TRIGGER IF EXISTS set_timestamp_system_settings ON system_settings;;
CREATE TRIGGER set_timestamp_system_settings
BEFORE UPDATE ON system_settings
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();;


-- 2. TABLE: users
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    mobile_number VARCHAR(15) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_synced BOOLEAN DEFAULT FALSE
);;

COMMENT ON TABLE users IS 'Stores user credentials and operational roles. Usernames are strictly mobile numbers.';;
COMMENT ON COLUMN users.user_id IS 'Unique UUID generated by the application framework.';;
COMMENT ON COLUMN users.mobile_number IS 'Acts as the login username.';;
COMMENT ON COLUMN users.password_hash IS 'Simple password hashing storage.';;
COMMENT ON COLUMN users.role IS 'Enforced values: SUPER_ADMIN, INVENTORY_ADMIN, POS_ADMIN.';;

DROP TRIGGER IF EXISTS set_timestamp_users ON users;;
CREATE TRIGGER set_timestamp_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();;


-- 3. TABLE: products
CREATE TABLE IF NOT EXISTS products (
    product_id UUID PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    barcode VARCHAR(100) UNIQUE,
    product_name VARCHAR(150) NOT NULL,
    category VARCHAR(100),
    brand VARCHAR(100),
    attributes JSONB,
    cost_price DECIMAL(10, 2) NOT NULL CHECK (cost_price > 0),
    profit_percentage DECIMAL(5, 2) DEFAULT 0.00,
    selling_price DECIMAL(10, 2) NOT NULL CHECK (selling_price > 0),
    current_stock INT NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_synced BOOLEAN DEFAULT FALSE
);;

COMMENT ON TABLE products IS 'Stores master inventory data. This table is optimized for a cap of 1,000 active unique SKUs.';;
COMMENT ON COLUMN products.product_id IS 'Unique UUID generated by the application framework.';;
COMMENT ON COLUMN products.sku IS 'Stock Keeping Unit (unique per product variant).';;
COMMENT ON COLUMN products.barcode IS 'Barcode string; nullable to support manual text typing if the scanner fails.';;
COMMENT ON COLUMN products.cost_price IS 'The acquisition price paid for the item.';;
COMMENT ON COLUMN products.profit_percentage IS 'Configurable profit margin percentage.';;
COMMENT ON COLUMN products.selling_price IS 'Calculated automatically as: cost_price * (1 + profit_percentage/100).';;
COMMENT ON COLUMN products.current_stock IS 'Real-time physical stock level on hand.';;

DROP TRIGGER IF EXISTS set_timestamp_products ON products;;
CREATE TRIGGER set_timestamp_products
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();;


-- 4. TABLE: sales_transactions
CREATE TABLE IF NOT EXISTS sales_transactions (
    transaction_id UUID PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    payment_mode VARCHAR(20) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    created_by UUID NOT NULL REFERENCES users(user_id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_synced BOOLEAN DEFAULT FALSE
);;

COMMENT ON TABLE sales_transactions IS 'Logs every completed point-of-sale transaction, tracking payment methods and bill totals.';;
COMMENT ON COLUMN sales_transactions.transaction_id IS 'Unique UUID generated by the application framework.';;
COMMENT ON COLUMN sales_transactions.invoice_number IS 'Structured bill/invoice identifier for Phase 6 printing.';;
COMMENT ON COLUMN sales_transactions.payment_mode IS 'Selected payment type (e.g., CASH, UPI, CARD).';;
COMMENT ON COLUMN sales_transactions.total_amount IS 'Grand total paid by the customer for the invoice.';;
COMMENT ON COLUMN sales_transactions.created_by IS 'Identifies the POS_ADMIN or SUPER_ADMIN processing the sale.';;


-- 5. TABLE: sales_items
CREATE TABLE IF NOT EXISTS sales_items (
    sales_item_id UUID PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES sales_transactions(transaction_id),
    product_id UUID NOT NULL REFERENCES products(product_id),
    quantity_sold INT NOT NULL CHECK (quantity_sold > 0),
    unit_price_at_sale DECIMAL(10, 2) NOT NULL
);;

COMMENT ON TABLE sales_items IS 'Provides a line-item, itemized breakdown of products within each specific sales transaction.';;
COMMENT ON COLUMN sales_items.sales_item_id IS 'Unique UUID generated by the application framework.';;
COMMENT ON COLUMN sales_items.transaction_id IS 'Links directly back to the parent sale invoice.';;
COMMENT ON COLUMN sales_items.product_id IS 'Links to the specific product purchased.';;
COMMENT ON COLUMN sales_items.quantity_sold IS 'Exact number of units purchased in this transaction.';;
COMMENT ON COLUMN sales_items.unit_price_at_sale IS 'Captures the exact price at the moment of sale, ignoring future price changes.';;


-- 6. TABLE: inventory_audit_logs
CREATE TABLE IF NOT EXISTS inventory_audit_logs (
    log_id UUID PRIMARY KEY,
    product_id UUID NOT NULL REFERENCES products(product_id),
    action_type VARCHAR(30) NOT NULL,
    previous_quantity INT NOT NULL,
    new_quantity INT NOT NULL,
    transaction_id UUID REFERENCES sales_transactions(transaction_id),
    updated_by UUID NOT NULL REFERENCES users(user_id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_synced BOOLEAN DEFAULT FALSE
);;

COMMENT ON TABLE inventory_audit_logs IS 'The core security ledger tracking explicit actions, user identities, and contextual reasons for stock changes.';;
COMMENT ON COLUMN inventory_audit_logs.log_id IS 'Unique UUID generated by the application framework.';;
COMMENT ON COLUMN inventory_audit_logs.action_type IS 'Enforced values: STOCK_ADD, STOCK_REDUCTION_SALE, STOCK_REDUCTION_LOSS, STOCK_CORRECTION.';;

-- ===========================================================================
-- PERFORMANCE OPTIMIZATION INDEXES
-- ===========================================================================
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);;
CREATE INDEX IF NOT EXISTS idx_audit_product ON inventory_audit_logs(product_id);;
CREATE INDEX IF NOT EXISTS idx_sales_items_tx ON sales_items(transaction_id);;

-- 7. TABLE: brands
CREATE TABLE IF NOT EXISTS brands (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    logo_base64 TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);;

COMMENT ON TABLE brands IS 'Stores brand names and their base64 logos.';;

DROP TRIGGER IF EXISTS set_timestamp_brands ON brands;;
CREATE TRIGGER set_timestamp_brands
BEFORE UPDATE ON brands
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();;

-- ===========================================================================
-- RETURNS MANAGEMENT SYSTEM EXTENSIONS (PHASE 1)
-- ===========================================================================

ALTER TABLE sales_transactions ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'COMPLETED';;
ALTER TABLE sales_transactions ADD COLUMN IF NOT EXISTS refunded_amount DECIMAL(10, 2) DEFAULT 0.00;;
ALTER TABLE sales_items ADD COLUMN IF NOT EXISTS quantity_returned INT DEFAULT 0;;
